### ISSUE TITLE
"mgmtsystem.action.type_action" is not in the selection

### ISSUE THREAD

**Issue by kris3324** [OCA/management-system#133] opened 2016-04-11 21:00 UTC
Hi all
I try to install v8 of management system but setup cannot create action type any idea
all the module setup is doing in the rules

module: mgmtsystem_action
version: 8.0

**Comment by kris3324** [comment] 2016-04-11 21:01
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 499, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 516, in dispatch
    result = self._call_function(**self.params)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 282, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 279, in checked_call
    return self.endpoint(*a, **kw)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 732, in __call__
    return self.method(*args, **kw)
  File "/usr/local/lib/python2.7/site-packages/openerp/http.py", line 375, in response_wrap
    response = f(*args, **kw)
  File "/var/packages/Odoo8/target/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/var/packages/Odoo8/target/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/module/module.py", line 497, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/registry.py", line 324, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 358, in load_modules
    loaded_modules, update_module)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 263, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 185, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='demo')
  File "/usr/local/lib/python2.7/site-packages/openerp/modules/loading.py", line 118, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 899, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 985, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 851, in parse
    self._tags[rec.tag](self.cr, rec, n, mode=mode)
  File "/usr/local/lib/python2.7/site-packages/openerp/tools/convert.py", line 765, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/addons/base/ir/ir_model.py", line 1047, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/packages/Odoo8/target/addons/base_action_rule/base_action_rule.py", line 177, in create
    new_id = create.origin(self, cr, uid, vals, context=context, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/packages/Odoo8/target/addons/mgmtsystem_action/mgmtsystem_action.py", line 65, in create
    return super(mgmtsystem_action, self).create(vals)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/var/packages/Odoo8/target/addons/crm_claim/crm_claim.py", line 161, in create
    return super(crm_claim, self).create(cr, uid, vals, context=context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/packages/Odoo8/target/addons/mail/mail_thread.py", line 377, in create
    thread_id = super(mail_thread, self).create(cr, uid, values, context=context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 332, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/models.py", line 3970, in create
    record = self.browse(self._create(old_vals))
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 235, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 464, in new_api
    result = method(self._model, cr, uid, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/models.py", line 4090, in _create
    self._check_selection_field_value(cr, user, field, vals[field], context=context)
  File "/usr/local/lib/python2.7/site-packages/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/openerp/models.py", line 2290, in _check_selection_field_value
    _('The value "%s" for the field "%s.%s" is not in the selection') % (value, self._name, field))
ParseError: "ValidateError
The value "immediate" for the field "mgmtsystem.action.type_action" is not in the selection" while parsing /var/packages/Odoo8/target/addons/mgmtsystem_action/demo_action.xml:6, near
<record id="demo_immediate" model="mgmtsystem.action">
      <field name="name">Add a comment to the revision</field>
      <field name="type_action">immediate</field>
      <field name="user_id" ref="base.user_root"/>
    </record>
Ok
```

**Comment by kris3324** [comment] 2016-04-11 21:06
crm_claim   Installed    8.0.1.0
mgmtsystem    Installed   8.0.1.0

**Comment by max3903** [comment] 2016-04-13 18:42
@kris3324 Can you trying updating to mgmtsystem_action version 8.0.1.2.0? 

It is working on Runbot:
http://3142723-8-0-e53c4f.runbot2.odoo-community.org/web#id=1&view_type=form&model=mgmtsystem.action&menu_id=240&action=271

**Comment by kris3324** [comment] 2016-04-13 18:55
Hi Max3903 this is this version i am tying to install

**Comment by max3903** [comment] 2016-04-13 19:02
@kris3324 can you install the module **without** the demo data and create an action to check that immediate action is available in the list of response type?

**Comment by kris3324** [comment] 2016-04-13 20:36
Sorry for my odoo level but i can"t uncheck demo data what is the procedure ?

**Comment by max3903** [comment] 2016-04-13 21:16
Create a new database and make sure the box  is unchecked.

**Comment by kris3324** [comment] 2016-04-14 12:43
Hi Max, everything is ok now it was exactly this, without demo data no problems
you are the Best 
Thanks a lot

**Comment by kris3324** [comment] 2016-04-14 17:46
Sorry i do too fast,
in fact action module is installed correctly but:
in menu management system / action,  when i create a new action, in type field i can see immediate, corrective ;preventive , perform.
 if i select corrective or preventive record is ok, if i chose immediate or perform no posible to record
i have a error see below
The value "immediate" for the field "mgmtsystem.action.type_action" is not in the selection.

**Comment by kris3324** [comment] 2016-04-30 15:55
Hi Maxime
any issue ?
kindly regards

**Comment by max3903** [comment] 2016-05-01 15:29
@kris3324 Can you check the content of `mgmtsystem_action/mgmtsystem_action.py` to make sure it includes:

```
type_action = fields.Selection([
                                   ('immediate', 'Immediate Action'),
                                   ('correction', 'Corrective Action'),
                                   ('prevention', 'Preventive Action'),
                                   ('improvement', 'Improvement Opportunity')
                                   ], 'Response Type')
```

https://github.com/OCA/management-system/blob/8.0/mgmtsystem_action/mgmtsystem_action.py#L38

**Comment by kris3324** [comment] 2016-05-04 18:45
Dear Maxime
Yes it is included

**Comment by kris3324** [comment] 2016-05-04 19:13
During creat action
fields  Type
with choice Corrective & Preventive it's OK
with choise Immediate or Improvement it'not ok

Odoo Warning

Valider l'erreur

The value "improvement" for the field "mgmtsystem.action.type_action" is not in the selection

Ok

mgmtsystem_action/mgmtsystem_action.py file have correct code what you mean

**Comment by dreispt** [comment] 2016-05-04 20:26
I'm not able to reproduce on Runbot.
Can you try there? https://runbot.odoo-community.org/runbot/repo/github-com-oca-management-system-128

I see a suspicious reference to `base_action_rule` in your traceback.
Are you using an clean database? Do you have any Automated Actions configured?

**Comment by kris3324** [comment] 2016-05-05 09:17
i start with database without demo data
my management system is 8.0.1.0.0 version
my action module is 8.0.1.2.0 version
what you mean suspicious reference to base_action_rule
yes there is automated action
Nom de l'action
mgmtsystem.action.window
Objet
mgmtsystem.action
Objet source
Utilisation de l'action
Type d'action
ir.actions.act_window
Fenêtre cible
Fenêtre courante
Paramètres généraux Sécurité
Vues
Type de vue
Formulaire
Mode d'affichage
tree
Voir la Réf.
mgmtsystem.action.tree 
Vue de recherche
Filtres
Valeur du domaine
Valeur du contexte
{}
Limite
80
Rafraîchissement automatique
0
Recherche automatique

Filtre

Restrict to lists

Aide
Vues
Séquence 
Type de vue 
Vue

**Comment by kris3324** [comment] 2016-05-26 14:38
dear team
any feedback regarding this problem 
do i need to delete automated action
kindly regards

**Comment by max3903** [comment] 2016-05-26 15:32
@kris3324 I ran out of idea and I can't reproduce it. The values of the selection seem to be available in the view but not on the object...

Can you provide more information on your system: 
- OS? Linux distribution? Version? 
- Python version? 
- PostgreSQL version? 
- Are you using Odoo from Odoo SA (https://github.com/odoo/odoo) or OCB from OCA (http://github.com/oca/ocb)?

**Comment by max3903** [comment] 2016-08-17 21:42
No answer. Closing.

**Closed as completed by max3903** 2016-08-17 21:42 UTC
Labels: work in progress
